AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Todo Application DynamoDB Table

Resources:
  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Todos
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

Outputs:
  TodosTableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt TodosTable.Arn
  TodosTableName:
    Description: Name of the DynamoDB table
    Value: !Ref TodosTable